#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.1.5"
URL="https://github.com/bwdutton/gallery3/archive/${VERSION}.zip"

dl $URL /usr/local/src

