#!/bin/bash -ex

dl() {
    [[ "$FAB_HTTP_PROXY" ]] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

REPO=bwdutton/gallery3
VERSION=$(gh_releases "$REPO" | grep -vi 'alpha\|beta\|rc' | sort -V | tail -1)
URL="https://github.com/$REPO/archive/${VERSION}.zip"

dl $URL /usr/local/src
