#!/bin/sh -ex

DB_NAME=gallery
DB_USER=gallery
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

WEBROOT=/var/www/gallery

# configure apache
a2enmod rewrite
a2dissite 000-default
a2ensite gallery

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# create database user with privileges on the database
service mysql start

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# configure php.ini to allow short php tag (<? ?> instead of <?php ?>)
CONF=/etc/php/7.0
sed -i 's|short_open_tag =.*|short_open_tag = On|' $CONF/cli/php.ini
sed -i 's|short_open_tag =.*|short_open_tag = On|' $CONF/apache2/php.ini

# unpack and configure gallery
unzip /usr/local/src/gallery*.zip -d /var/www/
mv /var/www/gallery3 $WEBROOT

mkdir -p $WEBROOT/var
chown www-data:www-data $WEBROOT/var

php $WEBROOT/installer/index.php -h localhost -u $DB_USER -p $DB_PASS -d $DB_NAME

/usr/lib/inithooks/bin/gallery.py --email="$ADMIN_MAIL" --pass="$ADMIN_PASS"

# Commenting out the cooliris js as it is not reachable
sed -i '/e.cooliris.com/s/^/#/' $WEBROOT/modules/slideshow/helpers/slideshow_theme.php

# stop mysql
service mysql stop

# cleanup
rm /usr/local/src/gallery*

