#!/bin/bash -e
# regenerate gallery2 mysql password

. /etc/default/inithooks

SETUP_PASS=$(mcookie)
PASSWORD=$(mcookie)

CONF=/etc/gallery2/config.php
update_conf1() { sed -i "s/^$1\(.*\)/$1 \'$2\');/" $CONF; }
update_conf2() { sed -i "s/^$1 = \(.*\)/$1 = \'$2\';/" $CONF; }

update_conf1 "\$gallery->setConfig('setup.password'," $SETUP_PASS
update_conf2 "\$storeConfig\['password'\]" $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=gallery2 --pass="$PASSWORD"

# remove innodb logfiles (workarounds really weird bug)
rm -f /var/lib/mysql/ib_logfile*

