#!/bin/bash -e
# regenerate gallery mysql password

. /etc/default/inithooks

CONF=/var/www/gallery/var/database.php
PASSWORD=$(mcookie)

sed -i "s|'pass'\(.*\)|'pass'     => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=gallery --pass="$PASSWORD"

# remove innodb logfiles (workarounds really weird bug)
rm -f /var/lib/mysql/ib_logfile*

